FrontEnd-Team3/final-project-pp

src/components/Chat/chat-list/index.js
src/pages/main/index.js
src/pages/search-page/index.js

feat:search css 수정 Chat css 수정

---

package-lock.json
package.json
src/App.css
src/App.js
src/components/AlertMessege/index.js
src/components/Button/style.js
src/components/Input/style.js
src/components/Layout/Footer/Footer.js
src/components/Layout/Header/Header.js
src/components/Pagination/index.js
src/components/ProductList/one-product.js
src/components/RecentlyClicked/RecentlyClicked.js
src/pages/main/components/free-product/FreeProduct.js
src/pages/main/components/used-product/UsedProduct.js
src/pages/main/index.js
src/pages/product-detail/components/other-products/OtherProducts.js
src/pages/product-detail/components/product-info/buttons.js
src/pages/product-detail/components/product-info/index.js
src/pages/product-register/index.js
src/pages/sign/components/sign-in/index.js
src/pages/sign/components/sign-up/index.js
src/pages/transaction/free-transaction/index.js
src/styles/common.js
src/styles/theme.js

1. theme.js 색상 변경
2. common.js 폰트 변경
3. 바뀐 색상 반영하여 basicButton 속성 수정
4. border-radius 속성 사라진 관계로 basicButton에서 shape 관련 속성 삭제 
개별 컴포넌트, 페이지에서 npm start 시 깨지지 않을 정도로만 코드를 수정해두었습니다!

feat: 변경 스타일 반영

---

public/mockServiceWorker.js
src/apis/chat.api.js
src/apis/product.api.js
src/apis/user.api.js
src/mock/chatList.js
src/mock/productsList.js
src/mocks/handlers.js
src/pages/main/index.js

feat: mockData clear

---

src/components/ProductList/index.js
src/components/ProductList/withoutPagination.js
src/components/Select/index.js
src/components/Select/style.js
src/mock/productsList.js
src/pages/transaction/free-transaction/index.js
src/pages/transaction/used-transaction/index.js
src/styles/theme.js

1. 필터링을 위한 **_select component_** 생성하여 작업하였습니다. 
(추후 마이페이지, 시세 그래프 등 동일 디자인의 select에 재사용 가능하도록.. 수정 염두에 두고 있음!)
2. 필터링을 위한 productList 목데이터 약간의 수정 있습니다.
3. theme.js PALETTE darkBlack 추가
+) ProductList/index.js, ProductList/withoutPagination.js -> grid-gap: 20px 추가하여 레이아웃 수정하였습니다.

feat: 중고거래, 무료나눔 페이지 필터링 구현 및 데이터 수정

---

src/components/Modal/Signin.js
src/pages/main/components/free-product/FreeProduct.js
src/pages/main/components/used-product/UsedProduct.js

- 토큰이 없으면 로그인 모달, 있으면 주소 변경 창 보이도록 함 (아직 토큰 검사 로직 구현 X)

chore: 토큰 있을 때만 주소 변경 창 보이도록 수정

---

src/pages/mypage/components/interest-product/components/InterestEndProductList.js
src/pages/mypage/components/register-product/components/StatusEndProductList.js
src/pages/mypage/components/transaction-history/index.js
src/pages/mypage/index.js

거래 내역, 관심 상품의 불필요한 셀렉트 삭제,
판매 완료 상품 css 추가

chore: 거래내역 관심상품 컴포넌트 불필요한 기능 정리

---

package-lock.json
package.json
src/components/Layout/Header/Header.js
src/pages/sign/SignValidation.js
src/pages/sign/components/controlled-input/ControlledInput.js
src/pages/sign/components/one-validate/OneValidate.js
src/pages/sign/components/sign-in/index.js
src/pages/sign/components/sign-up/index.js
src/routes/Routing.js

로그인 / 회원가입 페이지 유효성검사 구현 완료,
데이터까지 확인했습니다.

feat: 로그인, 회원가입 페이지 유효성검사 구현 완료, 데이터까지 확인

---

src/pages/mypage/components/nav/index.js
src/pages/mypage/components/register-product/account-privacy/index.js
src/pages/mypage/components/register-product/profile/index.js
src/pages/mypage/index.js

개인계정 관리 및 프로필 관리 css수정과 nav 구현 완료 했습니다.

chore: 개인계정 관리 및 프로필 관리 css수정과 nav 구현

---

src/pages/mypage/components/my-profile/index.js
src/pages/mypage/components/nav/index.js
src/pages/mypage/index.js

chore:마이페이지 nav바 위치 수정 완료 했습니다.

---

src/apis/auth.api.js
src/pages/my-page/components/HousekeepingBook/index.js
src/pages/my-page/components/InterestProduct/InterestEndProductList/index.js
src/pages/my-page/components/InterestProduct/index.js
src/pages/my-page/components/PurchasedItem/index.js
src/pages/my-page/components/RegisterProducts/StatusEndProductList/index.js
src/pages/my-page/components/RegisterProducts/index.js
src/pages/my-page/components/TransactionHistory/index.js

chore:회원가입 로직백엔드 연결

---

src/App.js
src/apis/auth.api.js
src/components/Layout/Header/index.js
src/context/auth.ctx.js
src/pages/sign/sign-in/index.js

로그아웃 기능과 토큰 유지 기능 추가하였습니다.
문제 사항으로는 로그인 되었을때 로그인 버튼이 바로 바뀌지 않고 새로고침을 해야 로그아웃으로 바뀌는
버그가 있습니다. 추후 고치도록 하겠습니다.

feat: 로그아웃 기능 및 토큰 유지

---

src/apis/auth.api.js
src/apis/user.query.api.js
src/consts/queryKey.js
src/pages/account-management/components/ManageProfile/components/MyprofileImage.js
src/pages/account-management/components/ManageProfile/index.js
src/pages/my-page/components/InterestProduct/InterestEndProductList/index.js
src/pages/my-page/components/InterestProduct/index.js
src/pages/my-page/components/MyProfile/index.js
src/pages/my-page/components/Nav/index.js
src/pages/my-page/components/RegisterProducts/index.js
src/pages/my-page/index.js

마이페이지 nav로 이동시 스크롤 조정되는 이벤트 추가하였습니다.
등록상품에 select 옵션 수정하였습니다.
관심상품에 판매 완료상품 태그 추가하였습니다.
추가로 유저 상품 데이터 userProductInfo로 추가해놨습니다.
추후 연동시 사용할 예정입니다.

My page sign up

---

src/apis/auth.api.js
src/pages/account-management/components/ManageProfile/components/MyprofileInfo.js
src/pages/account-management/components/ModifyInfo/components/ModifyInfoEdit.js
src/pages/account-management/components/ModifyInfo/index.js
src/pages/sign/sign-up/index.js

feat: 프로필/개인정보수정 페이지 완료

---

src/pages/product-register/components/editinputs.js

수정은 잘 돌아가요! 이미지 삭제나 추가는 조금 버그가 있을거에요. 그것도 마저 수정해서 올리겠습니다!

chore:수정만 다시 잘 돌아감 & 이미지 버그 수정예정

---

src/apis/product.query.api.js
src/consts/queryKey.js
src/pages/market-price/components/SearchBar/index.js
src/pages/market-price/components/SoldOut/index.js
src/routes/Routing.js

feat: 시세 페이지 api 받아오기 성공

---

src/components/Pagination/index.js
src/components/Select/index.js
src/pages/market-price/components/Graph/index.js
src/pages/market-price/components/SearchBar/index.js
src/pages/market-price/components/SelectBox/index.js
src/pages/market-price/components/SoldOut/index.js
src/pages/market-price/components/SoldOut/oneSoldOutProduct.js
src/pages/market-price/index.js
src/pages/product-register/components/editImages.js
src/pages/product-register/components/editinputs.js
src/utils/marketPriceData.js

Pair1 sue market price

---

src/apis/auth.api.js
src/apis/user.query.api.js
src/consts/queryKey.js
src/pages/my-page/components/RegisterProducts/StatusEndProductList/index.js
src/pages/my-page/components/RegisterProducts/index.js

feat:등록 물품 데이터 받아오기 완료

---

src/pages/product-register/components/Images.js
src/pages/product-register/components/inputs.js
src/pages/product-register/index.js
src/pages/search-page/index.js

design: 물품 등록 페이지 반응형 구현 완료

---

src/apis/product.api.js
src/apis/product.query.api.js
src/components/Layout/Footer/index.js
src/pages/product-register/components/inputs.js
src/pages/search-page/index.js

1. 검색 결과 중고 물품만 나오던 버그 수정하였습니다.
(현재 중고, 무료, 판매완료 모두 렌더링 되는데 판매완료는 빼고 렌더링할지? 등의 의견이 필요합니다 !)
2. 물품 등록 반응형 작업시 반영이 안된 부분 추가 수정하였습니다.
3. footer 반응형 구현 완료하였으나 디자인적으로 의견 있으시면 언제든 편하게 내주세요!

design: footer 반응형 구현 및 로직 수정

---

src/apis/product.api.js
src/apis/product.query.api.js
src/components/ProductList/oneProduct.js
src/components/ProductList/withPagination.js
src/components/ProductList/withoutPagination.js
src/components/Select/style.js
src/pages/main/components/Products/index.js
src/pages/product-register/components/Images.js
src/pages/product-register/components/editinputs.js
src/pages/product-register/components/inputs.js
src/pages/search-page/index.js
src/pages/transaction/free-transaction/index.js
src/pages/transaction/used-transaction/index.js

1. 검색 결과 판매중인 물품만 보이도록 로직 수정
2. main에 사용하는 withoutPagination 반응형 구현
3. 검색 페이지, 중고거래, 무료나눔 페이지에 사용되는 withPagination 반응형 구현
4. 물품 수정 페이지 등록 페이지와 동일하게 반응형 구현

design: 반응형 구현 및 수정 사항

---

src/apis/product.api.js
src/apis/product.query.api.js
src/components/Button/style.js
src/components/Layout/Header/index.js
src/components/Layout/index.js
src/components/ProductList/oneProduct.js
src/components/ProductList/withPagination.js
src/consts/queryKey.js
src/context/chatData.ctx.js
src/pages/Chat/ChatList/index.js
src/pages/Chat/Chatting/chatMain.js
src/pages/Chat/Chatting/index.js
src/pages/main/index.js
src/pages/product-detail/components/ProductInfo/Buttons/Buyer/bookmarkBtn.js
src/pages/product-detail/components/ProductInfo/Buttons/Buyer/startChatBtn.js
src/pages/product-detail/components/ProductInfo/index.js
src/pages/product-detail/index.js
src/pages/search-page/index.js
src/pages/sign/sign-in/index.js
src/pages/transaction/free-transaction/index.js
src/pages/transaction/used-transaction/index.js
src/utils/getChatIdx.js

- 채팅방 실시간 메시지 버그 수정 및 스크롤 이벤트 적용
- 중고물품, 무료나눔 페이지에 페이지네이션 적용

fix: 채팅 버그 수정 등

---

src/components/Pagination/index.js
src/pages/account-management/components/ModifyInfo/components/MyprofileImage.js
src/pages/account-management/components/ModifyInfo/index.js
src/pages/my-page/components/RegisterProducts/index.js
src/pages/sign/sign-up/index.js

fix: 계인정보 변경 모달 수정
